-- What is the Total Sales ?
SELECT SUM(TOTAL_PRICE) AS TOTAL_SALES FROM PIZZA_SALE;


-- What is the average value of an order ?
SELECT SUM(TOTAL_PRICE)/ COUNT(DISTINCT(ORDER_ID)) AS AVG_ORD_VALUE FROM PIZZA_SALE


-- What is the total nuMber of pizza sold ?
SELECT SUM(QUANTITY) AS TOTAL_PIZZA_SOLD FROM PIZZA_SALE;


-- What is the total number of Orders ?
SELECT COUNT(DISTINCT(ORDER_ID)) AS TOTAL_ORDERS FROM PIZZA_SALE;


-- WHATS THE AVERAGE AMOUNT OF PIZZA PER ORDER ?
SELECT 
(CAST(CAST(SUM(QUANTITY)AS DECIMAL(10,2))/
CAST(COUNT(DISTINCT ORDER_ID)AS DECIMAL(10,2))AS DECIMAL(10,2)))
AS AVG_PIZZA_PER_ORD
FROM pizza_sale 


--WHATS DAILY TREND OF ORDERS  ?
SELECT TO_CHAR(ORDER_DATE, 'Day') AS ORDER_DAY, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM PIZZA_SALE
GROUP BY TO_CHAR(ORDER_DATE, 'Day');


--HOURLY TREND OF TOTAL ORDERS ?
 SELECT TO_CHAR(ORDER_DATE, 'MONTH') AS MONTH_NAME,COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM PIZZA_SALE
GROUP BY TO_CHAR(ORDER_DATE, 'MONTH')
ORDER BY TOTAL_ORDERS DESC;


--PERCENTAGE OF SALES AS PER PIZZA CATEGORY
SELECT PIZZA_CATEGORY,SUM(TOTAL_PRICE) AS TOTAL_SALES,
(CAST ((SUM(TOTAL_PRICE)*100/
(SELECT SUM(TOTAL_PRICE) FROM PIZZA_SALE))AS DECIMAL(10,2))) AS PERCENT_SALES
FROM PIZZA_SALE
GROUP BY PIZZA_CATEGORY;


--PERCENTAGE OF SALES AS PER MONTH 
--(YOU CAN CHANGE THE WHERE CLAUSE NUMBER FROM 1-12 TO GET DATA OF THAT PARTICULAR MONTH)
SELECT PIZZA_CATEGORY,SUM(TOTAL_PRICE)AS TOTAL_SALES,(SUM(TOTAL_PRICE)*100/
(SELECT SUM(TOTAL_PRICE) FROM PIZZA_SALE 
WHERE EXTRACT(MONTH FROM ORDER_DATE)= 1)) AS PERCENT_SALES
FROM PIZZA_SALE
WHERE EXTRACT(MONTH FROM ORDER_DATE)= 1
GROUP BY PIZZA_CATEGORY;


--PERCENTAGE OF SALES AS PER PIZZA SIZE
SELECT PIZZA_SIZE, (SUM(TOTAL_PRICE)*100/ (SELECT SUM(TOTAL_PRICE) FROM PIZZA_SALE)) 
AS PERCENT_SALES
FROM PIZZA_SALE
GROUP BY PIZZA_SIZE
ORDER BY PERCENT_SALES DESC;


--TOTAL PIZZAS SOLD BY PIZZA CATEGORY
SELECT PIZZA_CATEGORY, SUM(TOTAL_PRICE) AS TOTAL_SALES
FROM PIZZA_SALE
GROUP BY PIZZA_CATEGORY;

-- TOP 5 HIGHEST SOLD PIZZA'S
SELECT DISTINCT PIZZA_NAME,SUM(TOTAL_PRICE)
FROM PIZZA_SALE
GROUP BY PIZZA_NAME
ORDER BY SUM(TOTAL_PRICE) DESC
LIMIT 5;


-- LEAST 5 SOLD PIZZA'S
SELECT DISTINCT PIZZA_NAME,SUM(TOTAL_PRICE)
FROM PIZZA_SALE
GROUP BY PIZZA_NAME
ORDER BY SUM(TOTAL_PRICE) ASC
LIMIT 5;


--SALES PER QUATER
SELECT 
EXTRACT(QUARTER FROM ORDER_DATE) AS QUARTER, 
SUM(TOTAL_PRICE) AS TOTAL_SALES 
FROM PIZZA_SALE 
GROUP BY EXTRACT(QUARTER FROM ORDER_DATE)
ORDER BY QUARTER;


-- 5 MOST SOLD PIZZA BY QUANTITY
SELECT PIZZA_NAME,SUM(QUANTITY)
FROM PIZZA_SALE
GROUP BY PIZZA_NAME
ORDER BY SUM(QUANTITY) DESC
LIMIT 5;


-- 5 LEAST SOLD PIZZA BY QUANTITY
SELECT PIZZA_NAME,SUM(QUANTITY)
FROM PIZZA_SALE
GROUP BY PIZZA_NAME
ORDER BY SUM(QUANTITY) ASC
LIMIT 5;